// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class HealthDataRecord {
  HealthDataRecord({
    this.type,
    this.value,
    this.unit,
    this.startTime,
    this.endTime,
  });

  String? type;

  double? value;

  String? unit;

  int? startTime;

  int? endTime;

  List<Object?> _toList() {
    return <Object?>[
      type,
      value,
      unit,
      startTime,
      endTime,
    ];
  }

  Object encode() {
    return _toList();  }

  static HealthDataRecord decode(Object result) {
    result as List<Object?>;
    return HealthDataRecord(
      type: result[0] as String?,
      value: result[1] as double?,
      unit: result[2] as String?,
      startTime: result[3] as int?,
      endTime: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HealthDataRecord || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class HealthWorkoutRecord {
  HealthWorkoutRecord({
    this.uuid,
    this.activityType,
    this.startTime,
    this.endTime,
    this.duration,
    this.totalDistance,
    this.totalEnergyBurned,
    this.sourceName,
    this.sourceId,
    this.isIndoor,
  });

  String? uuid;

  String? activityType;

  int? startTime;

  int? endTime;

  double? duration;

  double? totalDistance;

  double? totalEnergyBurned;

  String? sourceName;

  String? sourceId;

  bool? isIndoor;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      activityType,
      startTime,
      endTime,
      duration,
      totalDistance,
      totalEnergyBurned,
      sourceName,
      sourceId,
      isIndoor,
    ];
  }

  Object encode() {
    return _toList();  }

  static HealthWorkoutRecord decode(Object result) {
    result as List<Object?>;
    return HealthWorkoutRecord(
      uuid: result[0] as String?,
      activityType: result[1] as String?,
      startTime: result[2] as int?,
      endTime: result[3] as int?,
      duration: result[4] as double?,
      totalDistance: result[5] as double?,
      totalEnergyBurned: result[6] as double?,
      sourceName: result[7] as String?,
      sourceId: result[8] as String?,
      isIndoor: result[9] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HealthWorkoutRecord || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class HealthRouteLocation {
  HealthRouteLocation({
    this.latitude,
    this.longitude,
    this.altitude,
    this.speed,
    this.course,
    this.horizontalAccuracy,
    this.verticalAccuracy,
    this.timestamp,
  });

  double? latitude;

  double? longitude;

  double? altitude;

  double? speed;

  double? course;

  double? horizontalAccuracy;

  double? verticalAccuracy;

  int? timestamp;

  List<Object?> _toList() {
    return <Object?>[
      latitude,
      longitude,
      altitude,
      speed,
      course,
      horizontalAccuracy,
      verticalAccuracy,
      timestamp,
    ];
  }

  Object encode() {
    return _toList();  }

  static HealthRouteLocation decode(Object result) {
    result as List<Object?>;
    return HealthRouteLocation(
      latitude: result[0] as double?,
      longitude: result[1] as double?,
      altitude: result[2] as double?,
      speed: result[3] as double?,
      course: result[4] as double?,
      horizontalAccuracy: result[5] as double?,
      verticalAccuracy: result[6] as double?,
      timestamp: result[7] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HealthRouteLocation || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is HealthDataRecord) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is HealthWorkoutRecord) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is HealthRouteLocation) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return HealthDataRecord.decode(readValue(buffer)!);
      case 130: 
        return HealthWorkoutRecord.decode(readValue(buffer)!);
      case 131: 
        return HealthRouteLocation.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativeHealthKitApi {
  /// Constructor for [NativeHealthKitApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeHealthKitApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> requestPermissions() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_health_kit.NativeHealthKitApi.requestPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<List<HealthDataRecord>> readData(String type, int startTime, int endTime) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_health_kit.NativeHealthKitApi.readData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[type, startTime, endTime]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<HealthDataRecord>();
    }
  }

  Future<List<HealthWorkoutRecord>> readWorkouts(int startTime, int endTime) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_health_kit.NativeHealthKitApi.readWorkouts$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startTime, endTime]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<HealthWorkoutRecord>();
    }
  }

  Future<List<HealthRouteLocation>> readRoute(String workoutUUID) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_health_kit.NativeHealthKitApi.readRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[workoutUUID]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<HealthRouteLocation>();
    }
  }
}
