library;

import 'dart:io';
import 'package:path/path.dart' as p;

import '../types.dart';
import '../with_mod.dart';

// ---------------------------------------------------------------------------
// withLocales
// ---------------------------------------------------------------------------

/// Add supported locales to Info.plist (CFBundleLocalizations) and create
/// the corresponding .lproj directories with InfoPlist.strings files.
///
/// [locales]: map of locale code → map of string key → translated value.
/// e.g. `{ 'fr': { 'CFBundleDisplayName': 'Mon App' } }`
ConfigPlugin withLocales(Map<String, Map<String, String>> locales) {
  return (config) {
    // 1. Add CFBundleLocalizations to Info.plist.
    config = withMod(
      config,
      platform: 'ios',
      modName: 'infoPlist',
      action: (props) async {
        final plist = Map<String, dynamic>.from(
            (props.modResults as Map<String, dynamic>?) ?? {});
        final existing =
            List<String>.from(plist['CFBundleLocalizations'] as List? ?? []);
        for (final locale in locales.keys) {
          if (!existing.contains(locale)) existing.add(locale);
        }
        plist['CFBundleLocalizations'] = existing;
        return props.copyWith(modResults: plist);
      },
    );

    // 2. Write .lproj/InfoPlist.strings via dangerous mod.
    config = withMod(
      config,
      platform: 'ios',
      modName: 'dangerous',
      action: (props) async {
        if (props.modRequest.introspect) return props;
        await writeLocaleFiles(
          props.modRequest.platformProjectRoot,
          locales,
        );
        return props;
      },
    );

    return config;
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

Future<void> writeLocaleFiles(
  String iosRoot,
  Map<String, Map<String, String>> locales,
) async {
  for (final entry in locales.entries) {
    final locale = entry.key;
    final strings = entry.value;

    final lprojDir = Directory(p.join(iosRoot, 'Runner', '$locale.lproj'));
    if (!lprojDir.existsSync()) lprojDir.createSync(recursive: true);

    final infoPlistStrings = File(p.join(lprojDir.path, 'InfoPlist.strings'));
    final buf = StringBuffer('/* Generated by flutter_config_plugin */\n');
    for (final kv in strings.entries) {
      buf.writeln('"${kv.key}" = "${kv.value}";');
    }
    await infoPlistStrings.writeAsString(buf.toString());
  }
}
