// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class MathApiPigeonCodecReader: FlutterStandardReader {
}

private class MathApiPigeonCodecWriter: FlutterStandardWriter {
}

private class MathApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MathApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MathApiPigeonCodecWriter(data: data)
  }
}

class MathApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MathApiPigeonCodec(readerWriter: MathApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeMathApi {
  func add(a: Double, b: Double) throws -> Double
  func subtract(a: Double, b: Double) throws -> Double
  func multiply(a: Double, b: Double) throws -> Double
  func divide(a: Double, b: Double) throws -> Double
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeMathApiSetup {
  static var codec: FlutterStandardMessageCodec { MathApiPigeonCodec.shared }
  /// Sets up an instance of `NativeMathApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeMathApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let addChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_math.NativeMathApi.add\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aArg = args[0] as! Double
        let bArg = args[1] as! Double
        do {
          let result = try api.add(a: aArg, b: bArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addChannel.setMessageHandler(nil)
    }
    let subtractChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_math.NativeMathApi.subtract\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      subtractChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aArg = args[0] as! Double
        let bArg = args[1] as! Double
        do {
          let result = try api.subtract(a: aArg, b: bArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      subtractChannel.setMessageHandler(nil)
    }
    let multiplyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_math.NativeMathApi.multiply\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      multiplyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aArg = args[0] as! Double
        let bArg = args[1] as! Double
        do {
          let result = try api.multiply(a: aArg, b: bArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      multiplyChannel.setMessageHandler(nil)
    }
    let divideChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_math.NativeMathApi.divide\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      divideChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aArg = args[0] as! Double
        let bArg = args[1] as! Double
        do {
          let result = try api.divide(a: aArg, b: bArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      divideChannel.setMessageHandler(nil)
    }
  }
}
