library;

import 'dart:convert';

/// Result of a [mergeContents] call.
class MergeResult {
  const MergeResult({
    required this.contents,
    required this.didMerge,
    required this.didClear,
  });

  final String contents;

  /// True when new code was added (or replaced existing generated block).
  final bool didMerge;

  /// True when a previously generated block was removed (newSrc was empty).
  final bool didClear;
}

/// Insert (or replace) a tagged generated code block inside [src].
///
/// ```dart
/// final result = mergeContents(
///   src: mainActivityContent,
///   newSrc: 'import com.example.MyModule;',
///   tag: 'my-module',
///   anchor: RegExp(r'import android\.app\.Activity;'),
///   offset: 1,
///   comment: '//',
/// );
/// ```
///
/// The generated block looks like:
/// ```
/// // @generated begin my-module - <hash>
/// import com.example.MyModule;
/// // @generated end my-module
/// ```
MergeResult mergeContents({
  required String src,
  required String newSrc,
  required String tag,
  required Pattern anchor,
  int offset = 0,
  String comment = '//',
}) {
  final begin = '$comment @generated begin $tag';
  final end = '$comment @generated end $tag';

  // Remove existing block first (from previous runs).
  String cleaned = src;
  final blockPattern = RegExp(
    '$comment @generated begin $tag[\\s\\S]*?$comment @generated end $tag\\n?',
  );
  bool didClear = false;
  if (blockPattern.hasMatch(cleaned)) {
    cleaned = cleaned.replaceFirst(blockPattern, '');
    didClear = true;
  }

  if (newSrc.isEmpty) {
    return MergeResult(contents: cleaned, didMerge: false, didClear: didClear);
  }

  // Find anchor position.
  final match = anchor.allMatches(cleaned).firstOrNull;
  if (match == null) {
    // No anchor found; append at end.
    final hash = _shortHash(newSrc);
    final block = '\n$begin - $hash\n$newSrc\n$end\n';
    return MergeResult(
      contents: cleaned + block,
      didMerge: true,
      didClear: didClear,
    );
  }

  // Find insertion line (anchor line + offset).
  final lines = cleaned.split('\n');
  int anchorLine = 0;
  int charCount = 0;
  for (int i = 0; i < lines.length; i++) {
    charCount += lines[i].length + 1; // +1 for '\n'
    if (charCount > match.start) {
      anchorLine = i;
      break;
    }
  }

  final insertAt = (anchorLine + offset).clamp(0, lines.length);
  final hash = _shortHash(newSrc);
  lines.insertAll(insertAt, [
    '$begin - $hash',
    newSrc,
    end,
  ]);

  return MergeResult(
    contents: lines.join('\n'),
    didMerge: true,
    didClear: didClear,
  );
}

/// Remove a previously generated block identified by [tag].
MergeResult removeContents({
  required String src,
  required String tag,
  String comment = '//',
}) {
  return mergeContents(
    src: src,
    newSrc: '',
    tag: tag,
    anchor: RegExp(''),
    comment: comment,
  );
}

/// Create a generated header comment for a file.
String createGeneratedHeaderComment(String src, String tag, String comment) {
  final hash = _shortHash(src);
  return '$comment This file was generated by $tag - $hash';
}

String _shortHash(String content) {
  final bytes = utf8.encode(content);
  int hash = 0;
  for (final b in bytes) {
    hash = (hash * 31 + b) & 0xFFFFFFFF;
  }
  return hash.toRadixString(16).padLeft(8, '0');
}
