// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsHealthKitApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsHealthKitApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsHealthKitApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashHealthKitApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashHealthKitApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashHealthKitApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct HealthDataRecord: Hashable {
  var type: String? = nil
  var value: Double? = nil
  var unit: String? = nil
  var startTime: Int64? = nil
  var endTime: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HealthDataRecord? {
    let type: String? = nilOrValue(pigeonVar_list[0])
    let value: Double? = nilOrValue(pigeonVar_list[1])
    let unit: String? = nilOrValue(pigeonVar_list[2])
    let startTime: Int64? = nilOrValue(pigeonVar_list[3])
    let endTime: Int64? = nilOrValue(pigeonVar_list[4])

    return HealthDataRecord(
      type: type,
      value: value,
      unit: unit,
      startTime: startTime,
      endTime: endTime
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      value,
      unit,
      startTime,
      endTime,
    ]
  }
  static func == (lhs: HealthDataRecord, rhs: HealthDataRecord) -> Bool {
    return deepEqualsHealthKitApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashHealthKitApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HealthWorkoutRecord: Hashable {
  var uuid: String? = nil
  var activityType: String? = nil
  var startTime: Int64? = nil
  var endTime: Int64? = nil
  var duration: Double? = nil
  var totalDistance: Double? = nil
  var totalEnergyBurned: Double? = nil
  var sourceName: String? = nil
  var sourceId: String? = nil
  var isIndoor: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HealthWorkoutRecord? {
    let uuid: String? = nilOrValue(pigeonVar_list[0])
    let activityType: String? = nilOrValue(pigeonVar_list[1])
    let startTime: Int64? = nilOrValue(pigeonVar_list[2])
    let endTime: Int64? = nilOrValue(pigeonVar_list[3])
    let duration: Double? = nilOrValue(pigeonVar_list[4])
    let totalDistance: Double? = nilOrValue(pigeonVar_list[5])
    let totalEnergyBurned: Double? = nilOrValue(pigeonVar_list[6])
    let sourceName: String? = nilOrValue(pigeonVar_list[7])
    let sourceId: String? = nilOrValue(pigeonVar_list[8])
    let isIndoor: Bool? = nilOrValue(pigeonVar_list[9])

    return HealthWorkoutRecord(
      uuid: uuid,
      activityType: activityType,
      startTime: startTime,
      endTime: endTime,
      duration: duration,
      totalDistance: totalDistance,
      totalEnergyBurned: totalEnergyBurned,
      sourceName: sourceName,
      sourceId: sourceId,
      isIndoor: isIndoor
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      activityType,
      startTime,
      endTime,
      duration,
      totalDistance,
      totalEnergyBurned,
      sourceName,
      sourceId,
      isIndoor,
    ]
  }
  static func == (lhs: HealthWorkoutRecord, rhs: HealthWorkoutRecord) -> Bool {
    return deepEqualsHealthKitApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashHealthKitApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HealthRouteLocation: Hashable {
  var latitude: Double? = nil
  var longitude: Double? = nil
  var altitude: Double? = nil
  var speed: Double? = nil
  var course: Double? = nil
  var horizontalAccuracy: Double? = nil
  var verticalAccuracy: Double? = nil
  var timestamp: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HealthRouteLocation? {
    let latitude: Double? = nilOrValue(pigeonVar_list[0])
    let longitude: Double? = nilOrValue(pigeonVar_list[1])
    let altitude: Double? = nilOrValue(pigeonVar_list[2])
    let speed: Double? = nilOrValue(pigeonVar_list[3])
    let course: Double? = nilOrValue(pigeonVar_list[4])
    let horizontalAccuracy: Double? = nilOrValue(pigeonVar_list[5])
    let verticalAccuracy: Double? = nilOrValue(pigeonVar_list[6])
    let timestamp: Int64? = nilOrValue(pigeonVar_list[7])

    return HealthRouteLocation(
      latitude: latitude,
      longitude: longitude,
      altitude: altitude,
      speed: speed,
      course: course,
      horizontalAccuracy: horizontalAccuracy,
      verticalAccuracy: verticalAccuracy,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
      altitude,
      speed,
      course,
      horizontalAccuracy,
      verticalAccuracy,
      timestamp,
    ]
  }
  static func == (lhs: HealthRouteLocation, rhs: HealthRouteLocation) -> Bool {
    return deepEqualsHealthKitApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashHealthKitApi(value: toList(), hasher: &hasher)
  }
}

private class HealthKitApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return HealthDataRecord.fromList(self.readValue() as! [Any?])
    case 130:
      return HealthWorkoutRecord.fromList(self.readValue() as! [Any?])
    case 131:
      return HealthRouteLocation.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HealthKitApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HealthDataRecord {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? HealthWorkoutRecord {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? HealthRouteLocation {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HealthKitApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HealthKitApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HealthKitApiPigeonCodecWriter(data: data)
  }
}

class HealthKitApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HealthKitApiPigeonCodec(readerWriter: HealthKitApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeHealthKitApi {
  func requestPermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  func readData(type: String, startTime: Int64, endTime: Int64, completion: @escaping (Result<[HealthDataRecord], Error>) -> Void)
  func readWorkouts(startTime: Int64, endTime: Int64, completion: @escaping (Result<[HealthWorkoutRecord], Error>) -> Void)
  func readRoute(workoutUUID: String, completion: @escaping (Result<[HealthRouteLocation], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeHealthKitApiSetup {
  static var codec: FlutterStandardMessageCodec { HealthKitApiPigeonCodec.shared }
  /// Sets up an instance of `NativeHealthKitApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeHealthKitApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_health_kit.NativeHealthKitApi.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { _, reply in
        api.requestPermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    let readDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_health_kit.NativeHealthKitApi.readData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! String
        let startTimeArg = args[1] as! Int64
        let endTimeArg = args[2] as! Int64
        api.readData(type: typeArg, startTime: startTimeArg, endTime: endTimeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readDataChannel.setMessageHandler(nil)
    }
    let readWorkoutsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_health_kit.NativeHealthKitApi.readWorkouts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readWorkoutsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let startTimeArg = args[0] as! Int64
        let endTimeArg = args[1] as! Int64
        api.readWorkouts(startTime: startTimeArg, endTime: endTimeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readWorkoutsChannel.setMessageHandler(nil)
    }
    let readRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_health_kit.NativeHealthKitApi.readRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let workoutUUIDArg = args[0] as! String
        api.readRoute(workoutUUID: workoutUUIDArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readRouteChannel.setMessageHandler(nil)
    }
  }
}
